/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCliente;
import modelo.Estafador_datos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Comentario;
import modelo.Estafador;
import modelo.Etiketa;
import static modelo.ModeloProtocoloCliente.*;
import modelo.Usuario;



/**
 *
 * @author RojeruSan
 */
public class VistaJFrame_menu extends javax.swing.JFrame implements IVista{

    /**
     * Creates new form Principal
     */
       ControladorCliente controlador;
    public VistaJFrame_menu() {
        initComponents();
        this.setLocationRelativeTo(this);
       // setModeloUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_contenidoMenu = new javax.swing.JPanel();
        jPanel_menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel_home = new javax.swing.JLabel();
        jLabel_home1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel_botones = new javax.swing.JPanel();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jtext_nick = new java.awt.TextField();
        jtext_email = new java.awt.TextField();
        jtext_name = new java.awt.TextField();
        label_id_nick = new java.awt.Label();
        label_id_email = new java.awt.Label();
        label_id_nombre = new java.awt.Label();
        jtext_id = new java.awt.TextField();
        label_id = new java.awt.Label();
        jPanel_addTags = new javax.swing.JPanel();
        jButton_enviarTag = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_newTag = new javax.swing.JTextField();
        jPanel_superiorMenu = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField_saludo = new javax.swing.JTextField();
        jButton_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_contenidoMenu.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_contenidoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_menu.setBackground(new java.awt.Color(153, 153, 153));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        jPanel_menu.setBorder(dropShadowBorder1);
        jPanel_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_menuMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Usuarios");
        jButton1.setActionCommand("ACTION1");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tags");
        jButton4.setActionCommand("ACTION4");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setOpaque(true);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Comentarios");
        jButton3.setActionCommand("ACTION3");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setOpaque(true);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Estafadores");
        jButton2.setActionCommand("ACTION2");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jButton2.setOpaque(true);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel_home.setBackground(new java.awt.Color(0, 153, 255));
        jLabel_home.setForeground(new java.awt.Color(0, 153, 255));
        jLabel_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home_lock_open.png"))); // NOI18N
        jLabel_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_home.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel_home.setMinimumSize(new java.awt.Dimension(75, 75));
        jLabel_home.setPreferredSize(new java.awt.Dimension(75, 75));
        jLabel_home.setVerifyInputWhenFocusTarget(false);

        jLabel_home1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel_home1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel_home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home_lock_open.png"))); // NOI18N
        jLabel_home1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_home1.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel_home1.setMinimumSize(new java.awt.Dimension(75, 75));
        jLabel_home1.setPreferredSize(new java.awt.Dimension(75, 75));
        jLabel_home1.setVerifyInputWhenFocusTarget(false);

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Insertar usuario");
        jButton5.setActionCommand("REGISTER");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("en construcción");
        jButton6.setActionCommand("REGISTER");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.setOpaque(true);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(jPanel_menuLayout.createSequentialGroup()
                        .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_menuLayout.createSequentialGroup()
                        .addComponent(jLabel_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel_contenidoMenu.add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 210, 430));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        jPanel_contenidoMenu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 650, 240));

        jPanel_botones.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_botones.setToolTipText("");

        jButton_update.setText("Update");
        jButton_update.setActionCommand("UPDATE");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.setActionCommand("DELETE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jtext_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nickActionPerformed(evt);
            }
        });

        jtext_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_emailActionPerformed(evt);
            }
        });

        jtext_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nameActionPerformed(evt);
            }
        });

        label_id_nick.setAlignment(java.awt.Label.CENTER);
        label_id_nick.setBackground(new java.awt.Color(204, 255, 255));
        label_id_nick.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_id_nick.setText("Nick");

        label_id_email.setAlignment(java.awt.Label.CENTER);
        label_id_email.setBackground(new java.awt.Color(204, 255, 255));
        label_id_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_id_email.setText("Email");

        label_id_nombre.setAlignment(java.awt.Label.CENTER);
        label_id_nombre.setBackground(new java.awt.Color(204, 255, 255));
        label_id_nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_id_nombre.setText("Nombre");

        jtext_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_idActionPerformed(evt);
            }
        });

        label_id.setAlignment(java.awt.Label.CENTER);
        label_id.setBackground(new java.awt.Color(204, 255, 255));
        label_id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_id.setText("ID");

        javax.swing.GroupLayout jPanel_botonesLayout = new javax.swing.GroupLayout(jPanel_botones);
        jPanel_botones.setLayout(jPanel_botonesLayout);
        jPanel_botonesLayout.setHorizontalGroup(
            jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_botonesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_botonesLayout.createSequentialGroup()
                        .addComponent(label_id_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext_name, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_botonesLayout.createSequentialGroup()
                        .addComponent(label_id_email, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext_email, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_botonesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_botonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 38, Short.MAX_VALUE))
            .addGroup(jPanel_botonesLayout.createSequentialGroup()
                .addComponent(label_id_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jtext_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_botonesLayout.setVerticalGroup(
            jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_botonesLayout.createSequentialGroup()
                .addGroup(jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_botonesLayout.createSequentialGroup()
                        .addGroup(jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_botonesLayout.createSequentialGroup()
                                .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(label_id_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_botonesLayout.createSequentialGroup()
                                .addComponent(jtext_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtext_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_id_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_id_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_botonesLayout.createSequentialGroup()
                        .addComponent(jButton_update)
                        .addGap(7, 7, 7)
                        .addComponent(jButton_delete)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        label_id_email.getAccessibleContext().setAccessibleName("");

        jPanel_contenidoMenu.add(jPanel_botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 290, -1));

        jPanel_addTags.setBackground(new java.awt.Color(204, 255, 255));

        jButton_enviarTag.setText("Enviar");
        jButton_enviarTag.setActionCommand("ADDTAG");
        jButton_enviarTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_enviarTagActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Tag");

        jTextField_newTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_newTagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_addTagsLayout = new javax.swing.GroupLayout(jPanel_addTags);
        jPanel_addTags.setLayout(jPanel_addTagsLayout);
        jPanel_addTagsLayout.setHorizontalGroup(
            jPanel_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_addTagsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_newTag, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_enviarTag, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_addTagsLayout.setVerticalGroup(
            jPanel_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_addTagsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_addTagsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_newTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_enviarTag))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel_contenidoMenu.add(jPanel_addTags, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 250, 50));

        getContentPane().add(jPanel_contenidoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 60, 970, 420));

        jPanel_superiorMenu.setBackground(new java.awt.Color(0, 102, 204));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icono-menu1.png"))); // NOI18N
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTextField_saludo.setBackground(new java.awt.Color(0, 102, 204));
        jTextField_saludo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_saludo.setBorder(null);
        jTextField_saludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_saludoActionPerformed(evt);
            }
        });

        jButton_cerrar.setBackground(new java.awt.Color(0, 153, 255));
        jButton_cerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar.setText("X");
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_cerrar.setOpaque(true);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_superiorMenuLayout = new javax.swing.GroupLayout(jPanel_superiorMenu);
        jPanel_superiorMenu.setLayout(jPanel_superiorMenuLayout);
        jPanel_superiorMenuLayout.setHorizontalGroup(
            jPanel_superiorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superiorMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 693, Short.MAX_VALUE)
                .addComponent(jTextField_saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_superiorMenuLayout.setVerticalGroup(
            jPanel_superiorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superiorMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_superiorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_superiorMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jTextField_saludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_saludoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_saludoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setActionCommand("ACTION1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.out.println("pulso 1");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        System.out.println("pulso 3");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.out.println("pulso 4");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jPanel_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_menuMouseClicked
        // TODO add your handling code here:
       // this.jPanel_menu.setVisible(false);
    }//GEN-LAST:event_jPanel_menuMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    int x=210;
    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
          if(  jToggleButton1.isSelected()){
              jPanel_menu.setVisible(false);
              jPanel_menu.setSize(0, 0);
      }else{
              jPanel_menu.setVisible(true);
              jPanel_menu.setSize(160, 430);
      }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtext_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_idActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed

       String id=jtext_id.getText().toString();
       String name=jtext_name.getText().toString();
       String nick=jtext_nick.getText().toString();
       String email=jtext_email.getText().toString();
 
   //   System.out.println(id+" PUSLO "+  id +"-"+name+"  -"+email+" "+nick);
       // jButton_enviar.setActionCommand("DELETE");
  //  this.mensaje=id+SEPARADOR+name+SEPARADOR+nick+SEPARADOR+email;

        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int selectedRow=jTable.getSelectedRow();
        String id= defaultTableModel.getValueAt(selectedRow, 0).toString();
        jtext_id.setText(id);
        jtext_name.setText(defaultTableModel.getValueAt(selectedRow, 2).toString());
        jtext_email.setText(defaultTableModel.getValueAt(selectedRow, 3).toString());
        jtext_nick.setText(defaultTableModel.getValueAt(selectedRow, 1).toString());
        System.out.println("jTable.getSelectedRow() "+id);
    }//GEN-LAST:event_jTableMouseClicked

    private void jtext_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nameActionPerformed

    private void jtext_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nickActionPerformed

    private void jtext_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_emailActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTextField_newTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_newTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_newTagActionPerformed

    private void jButton_enviarTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_enviarTagActionPerformed
        // TODO add your handling code here:
        this.mensaje=jTextField_newTag.getText().toString();
    }//GEN-LAST:event_jButton_enviarTagActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJFrame_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_delete;
    public javax.swing.JButton jButton_enviarTag;
    private javax.swing.JButton jButton_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_home;
    private javax.swing.JLabel jLabel_home1;
    private javax.swing.JPanel jPanel_addTags;
    private javax.swing.JPanel jPanel_botones;
    private javax.swing.JPanel jPanel_contenidoMenu;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_superiorMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    public javax.swing.JTextField jTextField_newTag;
    private javax.swing.JTextField jTextField_saludo;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.TextField jtext_email;
    private java.awt.TextField jtext_id;
    private java.awt.TextField jtext_name;
    private java.awt.TextField jtext_nick;
    private java.awt.Label label_id;
    private java.awt.Label label_id_email;
    private java.awt.Label label_id_nick;
    private java.awt.Label label_id_nombre;
    // End of variables declaration//GEN-END:variables

// OVERWRITE M´S
    
    @Override
    public void mostrarRespuesta(String mensaje) { 
        
//         int rows = jTable.getRowCount();
// for(int i=0;i<rows;i++)
// ((DefaultTableModel)jTable.setModel(defaultTableModel)).removeRow(i);
        
        defaultTableModel.setRowCount(0);
        String nombreUsuario;
        String [] str=mensaje.split(SEPARADOR);
        String strProtocolo=str[0];
          jPanel_botones.setVisible(false);
          jPanel_addTags.setVisible(false);
        System.out.println("mostrarRespuesta FRAME MENU "+mensaje);
        switch (strProtocolo) {
            case LOGIN_OK:
                nombreUsuario=str[1];
               // System.out.println("**vista frame recibido del server  "+nombreUsuario);
                jTextField_saludo.setText("Bienvenido "+nombreUsuario);// o tengo e poner el nick??
                break;
            case CHECKBOX_REGISTRO_TRUE:
                nombreUsuario=str[1];
                jTextField_saludo.setText("Bienvenido "+nombreUsuario);
                break;
            case ACTION1:   //usuarios    
                resetTag();
                jPanel_botones.setVisible(true);
                this.list_usuarios=new ArrayList<>();
                setModeloUsuarios();
                rellenarUsarios(mensaje);
                setDatosUsuarios();
                break;
            case ACTION2:  //estafadores 
                mostrartable(true); 
                 //jPanel_botones.setVisible(false);
                setModeloEStafador();
                rellenarEstafador(mensaje); 
                setEstafdor();
                break; 
            case ACTION3: 
                mostrartable(true);
               // jPanel_botones.setVisible(false);
                setModeloComments();
                rellenarComments(mensaje);
                setComments();
                break;
                
            case ACTION4:  // add alguna tag
                //jPanel_botones.setVisible(false);
                resetLogin(); // cambiar nombre
                jPanel_addTags.setVisible(true);
                System.out.println("MENS "+mensaje);
                mostrartable(true);
                setModeloTags();
                rellenarTags(mensaje);
                mostrarEtiketas();
                break;
                
            case ACTION5:
                jPanel_addTags.setVisible(false);
                System.out.println("....."+ACTION5);
                break;
                
            case DELETE:  // add alguna tag
                JOptionPane.showMessageDialog(null, mensaje.substring(7),
                mensaje.substring(7), JOptionPane.INFORMATION_MESSAGE);
                break;
                
            case UPDATE: // add alguna tag
                JOptionPane.showMessageDialog(null, MENSAJE_INFORMACION,
                mensaje.substring(7), JOptionPane.INFORMATION_MESSAGE);
                break;
                
            case INSERT: // add alguna tag
                JOptionPane.showMessageDialog(null, MENSAJE_INFORMACION,
                mensaje.substring(7), JOptionPane.INFORMATION_MESSAGE);
                break;
                
            case ADDTAG: // add alguna tag
                JOptionPane.showMessageDialog(null, MENSAJE_INFORMACION,
                mensaje.substring(7), JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                System.err.println("ERROR vista Menu->default: " );
        }     
    }
   
    public void mostrartable(boolean visble){
         jTable.setVisible(visble);
         jTable.getTableHeader().setVisible(visble);
    }

//-------------------new pruebas
    private void setModeloUsuarios(){
        String[] cabecera={"codigo","nick", "nombre" , "email"};
        defaultTableModel.setColumnIdentifiers(cabecera);
        jTable.setModel(defaultTableModel);
    }
    
     private void setModeloEStafador(){
        String[] cabecera={"ID", "Datos del estafador"};
        defaultTableModel.setColumnIdentifiers(cabecera);
        jTable.setModel(defaultTableModel);
    }
     private void setModeloComments(){
        String[] cabecera={"Comentarios publicos", "nick", "ID"};
        defaultTableModel.setColumnIdentifiers(cabecera);
        jTable.setModel(defaultTableModel);
    }
        private void setModeloTags(){
        String[] cabecera={"ID","Valor"};
        defaultTableModel.setColumnIdentifiers(cabecera);
        jTable.setModel(defaultTableModel);
    }
     
    
    private void setDatosUsuarios(){
       // llenarLista();
        Object [] datos=new Object[defaultTableModel.getColumnCount()];
        int i=1;
        for(Usuario s:list_usuarios ){
                datos[0]=s.getCod_usuario();
                 datos[1]=s.getNombre_usuario();
                  datos[2]=s.getEmail();
                   datos[3]=s.getNick();
                  i++;
            defaultTableModel.addRow(datos);
        }
        jTable.setModel(defaultTableModel);
    }
    
        private void setEstafdor(){
        Object [] datos=new Object[defaultTableModel.getColumnCount()];
        int i=1;
           for(Estafador s:list_estafadores ){
                datos[0]=s.getId();
                 datos[1]=s.getDatos();
                  i++;
            defaultTableModel.addRow(datos);
        }
        jTable.setModel(defaultTableModel);
    }
    
   private void setComments(){
        Object [] datos=new Object[defaultTableModel.getColumnCount()];
        int i=1;
           for(Comentario c:list_comments ){
                datos[0]=c.getId();
                 datos[1]=c.getComentario();
                 datos[2]=c.getNick();
                  i++;
            defaultTableModel.addRow(datos);
        }
        jTable.setModel(defaultTableModel);
    }
    
   private void mostrarEtiketas(){
        Object [] datos=new Object[defaultTableModel.getColumnCount()];
        int i=1;
           for(Etiketa c:list_tags ){
                datos[0]=c.getId();
                 datos[1]=c.getValor();
                  i++;
            defaultTableModel.addRow(datos);
        }
        jTable.setModel(defaultTableModel);
    }
        
    //----------------FIN P
    @Override
    public void resetLogin() {
            jtext_id.setText("");
           jtext_name.setText("");
            jtext_nick.setText("");
            jtext_email.setText("");
    }
    
     public void resetTag() {
            jTextField_newTag.setText("");
    }

    @Override
    public void setControlador(ControladorCliente controlador) {
        this.controlador = controlador;
    }

    @Override
    public void hacerVisible() {
        setVisible(true);
      
       
    }
    
    @Override
    public void inicializar(){
       jButton1.addActionListener(controlador);
        jButton2.addActionListener(controlador);
        jButton3.addActionListener(controlador);
        jButton4.addActionListener(controlador);
        jButton5.addActionListener(controlador);
        jButton_delete.addActionListener(controlador);
        jButton_update.addActionListener(controlador);
        jButton_enviarTag.addActionListener(controlador); 
    }

   
    @Override
    public String getMensajeAEnviar() {
        this.mensaje="";
        if(jtext_id.getText().toString().isEmpty()){
            if(!jTextField_newTag.getText().isEmpty()){
                this.mensaje=jTextField_newTag.getText().toString();
            }
        }else{
             String id=jtext_id.getText().toString();
            String name=jtext_name.getText().toString();
            String nick=jtext_nick.getText().toString();
            String email=jtext_email.getText().toString();
            this.mensaje=id+SEPARADOR+name+SEPARADOR+nick+SEPARADOR+email; 
        }
      
        return  this.mensaje;

    }
    
 

    @Override
    public void cerrar() {
         this.dispose();
    }

    @Override
    public void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }



     private void rellenarUsarios(String mensaje) {
            Usuario u=null;
            this.list_usuarios=new ArrayList<>();
            int dosPuntos=mensaje.indexOf(":");
            String msg=mensaje.substring(dosPuntos+3);
           // System.out.println(msg);
            String cod, email, nick, nombre;
            String[]vstr=msg.split(";");
            for(String s : vstr){
                  String[]splitDatos=s.split(":");
                  cod=splitDatos[0];
                  email=splitDatos[1];
                   nick=splitDatos[2];
                    nombre=splitDatos[3];
                    u=new Usuario(cod, nombre, email, nick);
                    this.list_usuarios.add(u);
            }
               
        }
     private void rellenarEstafador(String mensaje) {
             Estafador e=null;
            this.list_estafadores=new ArrayList<>();
            int dosPuntos=mensaje.indexOf(":");
            String msg=mensaje.substring(dosPuntos+3);
            
            String datos, id;
            String[]vstr=msg.split(";");
            for(String s : vstr){
                  String[]splitDatos=s.split(":");
                  datos=splitDatos[0];
                  id=splitDatos[1];
                  e=new Estafador(id, datos);
                  this.list_estafadores.add(e);
            }    
     }  
     
     
     private void rellenarComments(String mensaje) {
         Comentario e=null;
            this.list_comments=new ArrayList<>();
            int dosPuntos=mensaje.indexOf(":");
            String msg=mensaje.substring(dosPuntos+3);
            
            String datos, id, nick;
            String[]vstr=msg.split(";");
            for(String s : vstr){
                  String[]splitDatos=s.split(":");
                  datos=splitDatos[0];
                  id=splitDatos[1];
                  nick=splitDatos[2];
                  e=new Comentario(id, datos, nick);
                  this.list_comments.add(e);
            }  
            System.out.println("lit "+list_comments.toString());
     }  
     
     private void rellenarTags(String mensaje) {
        Etiketa e=null;
            this.list_tags=new ArrayList<>();
            int dosPuntos=mensaje.indexOf(":");
            String msg=mensaje.substring(dosPuntos+3);

            String  id, valor;
            String[]vstr=msg.split(";");
            for(String s : vstr){
               
                  String[]splitDatos=s.split(":");
                  id=splitDatos[0];
                  valor=splitDatos[1];
                  e=new Etiketa(id, valor);
                  this.list_tags.add(e);
            }  
            System.out.println("lit "+list_tags.toString());
     }
   
    
 private DefaultTableModel defaultTableModel=new DefaultTableModel();
 private ArrayList<Estafador_datos> list=new ArrayList<>();
 private ArrayList<Usuario> list_usuarios;
 private ArrayList<Estafador> list_estafadores;
 private ArrayList<Comentario> list_comments;
 private ArrayList<Etiketa> list_tags;
 private String mensaje;

}
