/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCliente;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import modelo.objetos.Comentario;
import modelo.objetos.Estafador;
import modelo.objetos.Tag;
import static utils.ProtocoloCliente.*;
import modelo.objetos.Usuario;

import modelo.objetos.*;



/**
 *
 * @author RojeruSan
 */
public class VistaJFrame_menu extends javax.swing.JFrame implements IVista, ItemListener{

    ControladorCliente controlador;
    public VistaJFrame_menu() {
        initComponents();
        jPanel_filter.setVisible(false);
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel_contenidoMenu = new javax.swing.JPanel();
        jPanel_menu_lateral = new javax.swing.JPanel();
        jButton_menu_usuarios = new javax.swing.JButton();
        jButton_menu_tags = new javax.swing.JButton();
        jButton_menu_comment = new javax.swing.JButton();
        jButton_menu_estafadores = new javax.swing.JButton();
        jLabel_home = new javax.swing.JLabel();
        jLabel_home1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton_menu_categoria = new javax.swing.JButton();
        jPanel_usuario = new javax.swing.JPanel();
        jButton_update_usuario = new javax.swing.JButton();
        jButton_delete_usuario = new javax.swing.JButton();
        jtext_nick = new java.awt.TextField();
        jtext_email = new java.awt.TextField();
        jtext_name = new java.awt.TextField();
        label_id_nick = new java.awt.Label();
        label_id_email = new java.awt.Label();
        label_id_nombre = new java.awt.Label();
        jtext_id = new java.awt.TextField();
        label_id = new java.awt.Label();
        jPanel_tabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel_estafador = new javax.swing.JPanel();
        jButton_updateEstafador = new javax.swing.JButton();
        jButton_deleteEstafador = new javax.swing.JButton();
        jtext_datos_3estafador = new java.awt.TextField();
        jtext_datos_2estafador = new java.awt.TextField();
        jtext_datos_1estafador = new java.awt.TextField();
        label_dato3 = new java.awt.Label();
        label_dato2 = new java.awt.Label();
        label_dato1 = new java.awt.Label();
        jtext_idEstafador = new java.awt.TextField();
        label_id_estafador = new java.awt.Label();
        jPanel_comentario = new javax.swing.JPanel();
        jButton_updateComment = new javax.swing.JButton();
        jButton_deleteComment = new javax.swing.JButton();
        jtext_comment = new java.awt.TextField();
        jtext_comment_comment = new java.awt.TextField();
        jtext_nick_comment = new java.awt.TextField();
        label_comment = new java.awt.Label();
        label_comment_comment = new java.awt.Label();
        label_nickPublicado = new java.awt.Label();
        jtext_idComment = new java.awt.TextField();
        label_id_comentario = new java.awt.Label();
        jPanel_tag = new javax.swing.JPanel();
        jButton_updateTag = new javax.swing.JButton();
        jButton_deleteTag = new javax.swing.JButton();
        label_nombreTag = new java.awt.Label();
        jtext_idTag = new java.awt.TextField();
        label_id_tag = new java.awt.Label();
        jButton_enviarTags = new javax.swing.JButton();
        jtext_valor_tag = new javax.swing.JTextField();
        jPanel_categoria = new javax.swing.JPanel();
        jButton_updateCategory = new javax.swing.JButton();
        jButton_deleteCategory = new javax.swing.JButton();
        label_nombreCategory = new java.awt.Label();
        jtext_idCategoria = new java.awt.TextField();
        label_id_Categoria = new java.awt.Label();
        jButton_insertCategory = new javax.swing.JButton();
        jtext_valor_category = new javax.swing.JTextField();
        jPanel_filter = new javax.swing.JPanel();
        jText_filter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel_superiorMenu = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField_saludo = new javax.swing.JTextField();
        jButton_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setResizable(false);

        jPanel_contenidoMenu.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_contenidoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_menu_lateral.setBackground(new java.awt.Color(153, 153, 153));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        jPanel_menu_lateral.setBorder(dropShadowBorder1);
        jPanel_menu_lateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_menu_lateralMouseClicked(evt);
            }
        });

        jButton_menu_usuarios.setBackground(new java.awt.Color(153, 153, 153));
        jButton_menu_usuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_menu_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        jButton_menu_usuarios.setText("Usuarios");
        jButton_menu_usuarios.setActionCommand("MENU_USUARIO");
        jButton_menu_usuarios.setBorder(null);
        jButton_menu_usuarios.setContentAreaFilled(false);
        jButton_menu_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_menu_usuarios.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jButton_menu_usuarios.setOpaque(true);
        jButton_menu_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_menu_usuariosMouseClicked(evt);
            }
        });
        jButton_menu_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_usuariosActionPerformed(evt);
            }
        });

        jButton_menu_tags.setBackground(new java.awt.Color(0, 153, 255));
        jButton_menu_tags.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_menu_tags.setForeground(new java.awt.Color(255, 255, 255));
        jButton_menu_tags.setText("Tags");
        jButton_menu_tags.setActionCommand("MENU_TAG");
        jButton_menu_tags.setBorder(null);
        jButton_menu_tags.setContentAreaFilled(false);
        jButton_menu_tags.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_menu_tags.setOpaque(true);
        jButton_menu_tags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_menu_tagsMouseClicked(evt);
            }
        });
        jButton_menu_tags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_tagsActionPerformed(evt);
            }
        });

        jButton_menu_comment.setBackground(new java.awt.Color(0, 153, 255));
        jButton_menu_comment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_menu_comment.setForeground(new java.awt.Color(255, 255, 255));
        jButton_menu_comment.setText("Comentarios");
        jButton_menu_comment.setActionCommand("MENU_COMENTARIO");
        jButton_menu_comment.setBorder(null);
        jButton_menu_comment.setContentAreaFilled(false);
        jButton_menu_comment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_menu_comment.setOpaque(true);
        jButton_menu_comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_menu_commentMouseClicked(evt);
            }
        });

        jButton_menu_estafadores.setBackground(new java.awt.Color(153, 153, 153));
        jButton_menu_estafadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_menu_estafadores.setForeground(new java.awt.Color(255, 255, 255));
        jButton_menu_estafadores.setText("Estafadores");
        jButton_menu_estafadores.setActionCommand("MENU_ESTAFADOR");
        jButton_menu_estafadores.setBorder(null);
        jButton_menu_estafadores.setContentAreaFilled(false);
        jButton_menu_estafadores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_menu_estafadores.setMargin(new java.awt.Insets(2, 20, 2, 20));
        jButton_menu_estafadores.setOpaque(true);
        jButton_menu_estafadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_menu_estafadoresMouseClicked(evt);
            }
        });
        jButton_menu_estafadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_estafadoresActionPerformed(evt);
            }
        });

        jLabel_home.setBackground(new java.awt.Color(0, 153, 255));
        jLabel_home.setForeground(new java.awt.Color(0, 153, 255));
        jLabel_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home_lock_open.png"))); // NOI18N
        jLabel_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_home.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel_home.setMinimumSize(new java.awt.Dimension(75, 75));
        jLabel_home.setPreferredSize(new java.awt.Dimension(75, 75));
        jLabel_home.setVerifyInputWhenFocusTarget(false);

        jLabel_home1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel_home1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel_home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home_lock_open.png"))); // NOI18N
        jLabel_home1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_home1.setMaximumSize(new java.awt.Dimension(75, 75));
        jLabel_home1.setMinimumSize(new java.awt.Dimension(75, 75));
        jLabel_home1.setPreferredSize(new java.awt.Dimension(75, 75));
        jLabel_home1.setVerifyInputWhenFocusTarget(false);

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Insertar usuario");
        jButton5.setActionCommand("REGISTER");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton_menu_categoria.setBackground(new java.awt.Color(0, 153, 255));
        jButton_menu_categoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_menu_categoria.setForeground(new java.awt.Color(255, 255, 255));
        jButton_menu_categoria.setText("Categoría");
        jButton_menu_categoria.setActionCommand("MENU_CATEGORIA");
        jButton_menu_categoria.setBorder(null);
        jButton_menu_categoria.setContentAreaFilled(false);
        jButton_menu_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_menu_categoria.setOpaque(true);
        jButton_menu_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_menu_categoriaMouseClicked(evt);
            }
        });
        jButton_menu_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_menu_categoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menu_lateralLayout = new javax.swing.GroupLayout(jPanel_menu_lateral);
        jPanel_menu_lateral.setLayout(jPanel_menu_lateralLayout);
        jPanel_menu_lateralLayout.setHorizontalGroup(
            jPanel_menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menu_lateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_menu_comment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_menu_tags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(jPanel_menu_lateralLayout.createSequentialGroup()
                        .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_menu_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton_menu_categoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(jPanel_menu_lateralLayout.createSequentialGroup()
                        .addComponent(jLabel_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_menu_estafadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_menu_lateralLayout.setVerticalGroup(
            jPanel_menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menu_lateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_menu_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel_menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_home1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_menu_estafadores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_menu_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_menu_tags, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_menu_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jPanel_contenidoMenu.add(jPanel_menu_lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 210, 530));

        jPanel_usuario.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));
        jPanel_usuario.setToolTipText("");
        jPanel_usuario.setPreferredSize(new java.awt.Dimension(264, 150));

        jButton_update_usuario.setText("Actualizar");
        jButton_update_usuario.setActionCommand("UPDATE_USUARIO");
        jButton_update_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_update_usuarioActionPerformed(evt);
            }
        });

        jButton_delete_usuario.setText("Eliminar");
        jButton_delete_usuario.setActionCommand("DELETE_USUARIO");
        jButton_delete_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_usuarioActionPerformed(evt);
            }
        });

        jtext_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nickActionPerformed(evt);
            }
        });

        jtext_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_emailActionPerformed(evt);
            }
        });

        jtext_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nameActionPerformed(evt);
            }
        });

        label_id_nick.setBackground(new java.awt.Color(204, 255, 255));
        label_id_nick.setText("Nick");

        label_id_email.setBackground(new java.awt.Color(204, 255, 255));
        label_id_email.setText("Email");

        label_id_nombre.setBackground(new java.awt.Color(204, 255, 255));
        label_id_nombre.setText("Nombre");

        jtext_id.setEditable(false
        );
        jtext_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_idActionPerformed(evt);
            }
        });

        label_id.setBackground(new java.awt.Color(204, 255, 255));
        label_id.setText("ID");

        javax.swing.GroupLayout jPanel_usuarioLayout = new javax.swing.GroupLayout(jPanel_usuario);
        jPanel_usuario.setLayout(jPanel_usuarioLayout);
        jPanel_usuarioLayout.setHorizontalGroup(
            jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                        .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                                .addComponent(label_id_email, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtext_email, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                                .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_id_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtext_name, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jtext_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton_update_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_delete_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 106, Short.MAX_VALUE))
                    .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                        .addComponent(label_id_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_usuarioLayout.setVerticalGroup(
            jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                        .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                                .addComponent(label_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_id_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                                .addComponent(jtext_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtext_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_id_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_id_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_usuarioLayout.createSequentialGroup()
                        .addComponent(jButton_update_usuario)
                        .addGap(7, 7, 7)
                        .addComponent(jButton_delete_usuario)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        label_id_email.getAccessibleContext().setAccessibleName("");

        jPanel_contenidoMenu.add(jPanel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 370, 150));

        jPanel_tabla.setForeground(new java.awt.Color(51, 153, 255));
        java.awt.GridBagLayout jPanel_tablaLayout = new java.awt.GridBagLayout();
        jPanel_tablaLayout.columnWidths = new int[] {0, 5, 0};
        jPanel_tablaLayout.rowHeights = new int[] {0, 5, 0};
        jPanel_tabla.setLayout(jPanel_tablaLayout);

        jScrollPane2.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable.setAutoCreateRowSorter(true);
        jTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setRowHeight(20);
        jTable.setRowMargin(2);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
            jTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 819;
        gridBagConstraints.ipady = 211;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 18);
        jPanel_tabla.add(jScrollPane2, gridBagConstraints);

        jPanel_contenidoMenu.add(jPanel_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 870, 260));

        jPanel_estafador.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_estafador.setBorder(javax.swing.BorderFactory.createTitledBorder("Estafadores"));
        jPanel_estafador.setToolTipText("");

        jButton_updateEstafador.setText("Actualizar");
        jButton_updateEstafador.setActionCommand("UPDATE");
        jButton_updateEstafador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateEstafadorActionPerformed(evt);
            }
        });

        jButton_deleteEstafador.setText("Eliminar");
        jButton_deleteEstafador.setActionCommand("DELETE");
        jButton_deleteEstafador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteEstafadorActionPerformed(evt);
            }
        });

        jtext_datos_3estafador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_datos_3estafadorActionPerformed(evt);
            }
        });

        jtext_datos_2estafador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_datos_2estafadorActionPerformed(evt);
            }
        });

        jtext_datos_1estafador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_datos_1estafadorActionPerformed(evt);
            }
        });

        label_dato3.setBackground(new java.awt.Color(204, 255, 255));
        label_dato3.setText("Dato 3");

        label_dato2.setBackground(new java.awt.Color(204, 255, 255));
        label_dato2.setText("Dato 2");

        label_dato1.setBackground(new java.awt.Color(204, 255, 255));
        label_dato1.setText("Dato 1");

        jtext_idEstafador.setEditable(false
        );
        jtext_idEstafador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_idEstafadorActionPerformed(evt);
            }
        });

        label_id_estafador.setBackground(new java.awt.Color(204, 255, 255));
        label_id_estafador.setText("ID");

        javax.swing.GroupLayout jPanel_estafadorLayout = new javax.swing.GroupLayout(jPanel_estafador);
        jPanel_estafador.setLayout(jPanel_estafadorLayout);
        jPanel_estafadorLayout.setHorizontalGroup(
            jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_estafadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label_dato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_id_estafador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label_dato2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dato3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_estafadorLayout.createSequentialGroup()
                        .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtext_datos_1estafador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_idEstafador, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_datos_2estafador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_updateEstafador, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jButton_deleteEstafador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_estafadorLayout.createSequentialGroup()
                        .addComponent(jtext_datos_3estafador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_estafadorLayout.setVerticalGroup(
            jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_estafadorLayout.createSequentialGroup()
                .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtext_idEstafador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id_estafador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_updateEstafador, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_estafadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_dato1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_datos_1estafador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_dato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_datos_2estafador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_estafadorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_deleteEstafador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_estafadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtext_datos_3estafador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel_contenidoMenu.add(jPanel_estafador, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 27, 370, 150));

        jPanel_comentario.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_comentario.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentarios"));
        jPanel_comentario.setToolTipText("");

        jButton_updateComment.setText("Actualizar");
        jButton_updateComment.setActionCommand("UPDATE_COMMENT");
        jButton_updateComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateCommentActionPerformed(evt);
            }
        });

        jButton_deleteComment.setText("Eliminar");
        jButton_deleteComment.setActionCommand("DELETE_COMMENT");
        jButton_deleteComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteCommentActionPerformed(evt);
            }
        });

        jtext_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_commentActionPerformed(evt);
            }
        });

        jtext_comment_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_comment_commentActionPerformed(evt);
            }
        });

        jtext_nick_comment.setEditable(false);
        jtext_nick_comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nick_commentActionPerformed(evt);
            }
        });

        label_comment.setBackground(new java.awt.Color(204, 255, 255));
        label_comment.setText("Dato 3");

        label_comment_comment.setBackground(new java.awt.Color(204, 255, 255));
        label_comment_comment.setText("Comentario");

        label_nickPublicado.setBackground(new java.awt.Color(204, 255, 255));
        label_nickPublicado.setText("Nick ");

        jtext_idComment.setEditable(false
        );
        jtext_idComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_idCommentActionPerformed(evt);
            }
        });

        label_id_comentario.setBackground(new java.awt.Color(204, 255, 255));
        label_id_comentario.setText("ID");

        javax.swing.GroupLayout jPanel_comentarioLayout = new javax.swing.GroupLayout(jPanel_comentario);
        jPanel_comentario.setLayout(jPanel_comentarioLayout);
        jPanel_comentarioLayout.setHorizontalGroup(
            jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_comentarioLayout.createSequentialGroup()
                        .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_nickPublicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_id_comentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                        .addComponent(label_comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_comentarioLayout.createSequentialGroup()
                        .addComponent(label_comment_comment, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                        .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtext_nick_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_comment_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtext_idComment, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_updateComment, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jButton_deleteComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jtext_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel_comentarioLayout.setVerticalGroup(
            jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtext_idComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_id_comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_updateComment, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext_nick_comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nickPublicado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_deleteComment))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel_comentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                        .addComponent(label_comment_comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_comentarioLayout.createSequentialGroup()
                        .addComponent(jtext_comment_comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtext_comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        label_nickPublicado.getAccessibleContext().setAccessibleName("Nick publica");

        jPanel_contenidoMenu.add(jPanel_comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 370, 150));

        jPanel_tag.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_tag.setBorder(javax.swing.BorderFactory.createTitledBorder("Tag"));
        jPanel_tag.setToolTipText("");

        jButton_updateTag.setText("Actualizar");
        jButton_updateTag.setActionCommand("UPDATE_TAG");
        jButton_updateTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateTagActionPerformed(evt);
            }
        });

        jButton_deleteTag.setText("Eliminar");
        jButton_deleteTag.setActionCommand("DELETE_TAG");
        jButton_deleteTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteTagActionPerformed(evt);
            }
        });

        label_nombreTag.setBackground(new java.awt.Color(204, 255, 255));
        label_nombreTag.setText("Valor");

        jtext_idTag.setEditable(false
        );
        jtext_idTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_idTagActionPerformed(evt);
            }
        });

        label_id_tag.setBackground(new java.awt.Color(204, 255, 255));
        label_id_tag.setText("ID");

        jButton_enviarTags.setText("Insertar");
        jButton_enviarTags.setActionCommand("INSERT_TAG");
        jButton_enviarTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_enviarTagsActionPerformed(evt);
            }
        });

        jtext_valor_tag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_valor_tagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_tagLayout = new javax.swing.GroupLayout(jPanel_tag);
        jPanel_tag.setLayout(jPanel_tagLayout);
        jPanel_tagLayout.setHorizontalGroup(
            jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_nombreTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_id_tag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tagLayout.createSequentialGroup()
                        .addComponent(jtext_idTag, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(jtext_valor_tag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_enviarTags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_updateTag, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jButton_deleteTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_tagLayout.setVerticalGroup(
            jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tagLayout.createSequentialGroup()
                .addGroup(jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_id_tag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_updateTag, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_tagLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtext_idTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_tagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtext_valor_tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_deleteTag))
                    .addComponent(label_nombreTag, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_enviarTags)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel_contenidoMenu.add(jPanel_tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 140));

        jPanel_categoria.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_categoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));
        jPanel_categoria.setToolTipText("");

        jButton_updateCategory.setText("Actualizar");
        jButton_updateCategory.setActionCommand("UPDATE_CATEGORIA");
        jButton_updateCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateCategoryActionPerformed(evt);
            }
        });

        jButton_deleteCategory.setText("Eliminar");
        jButton_deleteCategory.setActionCommand("DELETE_CATEGORIA");
        jButton_deleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteCategoryActionPerformed(evt);
            }
        });

        label_nombreCategory.setBackground(new java.awt.Color(204, 255, 255));
        label_nombreCategory.setText("Valor");

        jtext_idCategoria.setEditable(false
        );
        jtext_idCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_idCategoriaActionPerformed(evt);
            }
        });

        label_id_Categoria.setBackground(new java.awt.Color(204, 255, 255));
        label_id_Categoria.setText("ID");

        jButton_insertCategory.setText("Insertar");
        jButton_insertCategory.setActionCommand("INSERT_CATEGORIA");
        jButton_insertCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertCategoryActionPerformed(evt);
            }
        });

        jtext_valor_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_valor_categoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_categoriaLayout = new javax.swing.GroupLayout(jPanel_categoria);
        jPanel_categoria.setLayout(jPanel_categoriaLayout);
        jPanel_categoriaLayout.setHorizontalGroup(
            jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_categoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_nombreCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_id_Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_categoriaLayout.createSequentialGroup()
                        .addComponent(jtext_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(jtext_valor_category))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_insertCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_updateCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jButton_deleteCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_categoriaLayout.setVerticalGroup(
            jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_categoriaLayout.createSequentialGroup()
                .addGroup(jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_id_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_updateCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_categoriaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtext_idCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_categoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtext_valor_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_deleteCategory))
                    .addComponent(label_nombreCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_insertCategory)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel_contenidoMenu.add(jPanel_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 140));

        jText_filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jText_filterKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUSCAR");

        javax.swing.GroupLayout jPanel_filterLayout = new javax.swing.GroupLayout(jPanel_filter);
        jPanel_filter.setLayout(jPanel_filterLayout);
        jPanel_filterLayout.setHorizontalGroup(
            jPanel_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_filterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jText_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel_filterLayout.setVerticalGroup(
            jPanel_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_filterLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel_contenidoMenu.add(jPanel_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 350, 50));

        getContentPane().add(jPanel_contenidoMenu, java.awt.BorderLayout.CENTER);

        jPanel_superiorMenu.setBackground(new java.awt.Color(0, 102, 204));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icono-menu1.png"))); // NOI18N
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTextField_saludo.setBackground(new java.awt.Color(0, 102, 204));
        jTextField_saludo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_saludo.setBorder(null);
        jTextField_saludo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_saludoActionPerformed(evt);
            }
        });

        jButton_cerrar.setBackground(new java.awt.Color(0, 153, 255));
        jButton_cerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar.setText("X");
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_cerrar.setOpaque(true);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_superiorMenuLayout = new javax.swing.GroupLayout(jPanel_superiorMenu);
        jPanel_superiorMenu.setLayout(jPanel_superiorMenuLayout);
        jPanel_superiorMenuLayout.setHorizontalGroup(
            jPanel_superiorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superiorMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 845, Short.MAX_VALUE)
                .addComponent(jTextField_saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_superiorMenuLayout.setVerticalGroup(
            jPanel_superiorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_superiorMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_superiorMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_superiorMenu, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jTextField_saludoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_saludoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_saludoActionPerformed

    private void jButton_menu_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_usuariosActionPerformed
        // TODO add your handling code here:
        jButton_menu_usuarios.setActionCommand(MENU_USUARIO);
    }//GEN-LAST:event_jButton_menu_usuariosActionPerformed

    private void jButton_menu_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_menu_usuariosMouseClicked
        System.out.println("jButton_menu_usuariosMouseClicked");
    }//GEN-LAST:event_jButton_menu_usuariosMouseClicked

    private void jButton_menu_tagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_tagsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_menu_tagsActionPerformed

    private void jButton_menu_commentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_menu_commentMouseClicked
        // TODO add your handling code here:
        System.out.println("pulso 3");
    }//GEN-LAST:event_jButton_menu_commentMouseClicked

    private void jButton_menu_tagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_menu_tagsMouseClicked
        // TODO add your handling code here:
        System.out.println("pulso 4");
    }//GEN-LAST:event_jButton_menu_tagsMouseClicked

    private void jPanel_menu_lateralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_menu_lateralMouseClicked
        // TODO add your handling code here:
       // this.jPanel_menu.setVisible(false);
    }//GEN-LAST:event_jPanel_menu_lateralMouseClicked

    private void jButton_menu_estafadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_menu_estafadoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_menu_estafadoresMouseClicked

    private void jButton_menu_estafadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_estafadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_menu_estafadoresActionPerformed

    int x=210;
    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
          if(  jToggleButton1.isSelected()){
              jPanel_menu_lateral.setVisible(false);
              jPanel_menu_lateral.setSize(0, 0);
      }else{
              jPanel_menu_lateral.setVisible(true);
              jPanel_menu_lateral.setSize(160, 430);
      }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtext_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_idActionPerformed

    private void jButton_delete_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_usuarioActionPerformed
            String x;
            String id=jtext_id.getText().toString();
            String name=jtext_name.getText().toString();
            String nick=jtext_nick.getText().toString();
            String email=jtext_email.getText().toString();
            x=id+SEPARADOR+name+SEPARADOR+nick+SEPARADOR+email; 
            setMensaje(x);
       
    }//GEN-LAST:event_jButton_delete_usuarioActionPerformed

    // mira q tabla ha sido seleccionado -- coje los datos y lo mete en el cuadro superior
    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int selectedRow=jTable.getSelectedRow();
        String id= defaultTableModel.getValueAt(selectedRow, 0).toString();
        
        switch(jTable.getName()){
            case TABLA_USUARIO:
                jtext_id.setText(id);
                jtext_name.setText(defaultTableModel.getValueAt(selectedRow, 2).toString());
                jtext_email.setText(defaultTableModel.getValueAt(selectedRow, 3).toString());
                jtext_nick.setText(defaultTableModel.getValueAt(selectedRow, 1).toString());
                break;
            case TABLA_ESTAFADOR:
                ocultarCamposestafador(false);
                jtext_idEstafador.setText(id);
                String nombreEstafador, urlestafador, tel_estafador, email_estafador;
                String[] s=defaultTableModel.getValueAt(selectedRow, 1).toString().split(",");
                
                if(s.length==1 && s[0].equals("sin_datos")){
                      jtext_datos_1estafador.setText("No consta ningun dato");
                }else if(s.length==2){
                     jtext_datos_1estafador.setText(s[0]);
                     label_dato2.setVisible(true);
                     jtext_datos_2estafador.setVisible(true);
                     jtext_datos_2estafador.setText(s[1]);
                }else if(s.length==3){
                     ocultarCamposestafador(true);
                     jtext_datos_1estafador.setText(s[0]);
                     jtext_datos_2estafador.setText(s[1]);
                     jtext_datos_3estafador.setText(s[2]);
                }else if(s.length==4){
                    ocultarCamposestafador(true);
                     jtext_datos_1estafador.setText(s[0]);
                     jtext_datos_2estafador.setText(s[1]);
                     jtext_datos_3estafador.setText(s[2]);
                }else{
                     jtext_datos_1estafador.setText(s[0]);
                }
                break;
            case TABLA_COMENTARIOS:
                jtext_idComment.setText(id);
                jtext_nick_comment.setText(defaultTableModel.getValueAt(selectedRow, 1).toString());
                jtext_comment_comment.setText(defaultTableModel.getValueAt(selectedRow, 2).toString());
                break;
             case TABLA_TAGS:
                  jtext_idTag.setText(id);
                  jtext_valor_tag.setText(defaultTableModel.getValueAt(selectedRow, 1).toString()); 
                break; 
            case TABLA_CATEGORIA:
                  jtext_idCategoria.setText(id);
                  jtext_valor_category.setText(defaultTableModel.getValueAt(selectedRow, 1).toString()); 
                break;     
             default:
                    JOptionPane.showMessageDialog(null, "Ha surgido un error."); 
        }

     
    }//GEN-LAST:event_jTableMouseClicked

    private void jtext_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nameActionPerformed

    private void jtext_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nickActionPerformed

    private void jtext_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_emailActionPerformed

    private void jButton_update_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_update_usuarioActionPerformed
           String x;
            String id=jtext_id.getText().toString();
            String name=jtext_name.getText().toString();
            String nick=jtext_nick.getText().toString();
            String email=jtext_email.getText().toString();
            x=id+SEPARADOR+name+SEPARADOR+nick+SEPARADOR+email; 
            setMensaje(x);
    }//GEN-LAST:event_jButton_update_usuarioActionPerformed

    private void jtext_valor_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_valor_tagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_valor_tagActionPerformed

    private void jButton_enviarTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_enviarTagsActionPerformed
        // TODO add your handling code here:
        this.mensaje=jtext_valor_tag.getText().toString();
    }//GEN-LAST:event_jButton_enviarTagsActionPerformed

    private void jButton_menu_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_menu_categoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_menu_categoriaMouseClicked

    private void jButton_menu_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_menu_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_menu_categoriaActionPerformed

    private void jButton_updateEstafadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateEstafadorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_updateEstafadorActionPerformed

    private void jButton_deleteEstafadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteEstafadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_deleteEstafadorActionPerformed

    private void jtext_datos_3estafadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_datos_3estafadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_datos_3estafadorActionPerformed

    private void jtext_datos_2estafadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_datos_2estafadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_datos_2estafadorActionPerformed

    private void jtext_datos_1estafadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_datos_1estafadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_datos_1estafadorActionPerformed

    private void jtext_idEstafadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_idEstafadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_idEstafadorActionPerformed

    private void jButton_updateCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_updateCommentActionPerformed

    private void jButton_deleteCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_deleteCommentActionPerformed

    private void jtext_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_commentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_commentActionPerformed

    private void jtext_comment_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_comment_commentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_comment_commentActionPerformed

    private void jtext_nick_commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nick_commentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nick_commentActionPerformed

    private void jtext_idCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_idCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_idCommentActionPerformed

    private void jButton_updateTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateTagActionPerformed
        // TODO add your handling code here:
      jButton_updateTag.setActionCommand(UPDATE_TAG);
    }//GEN-LAST:event_jButton_updateTagActionPerformed

    private void jButton_deleteTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_deleteTagActionPerformed

    private void jtext_idTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_idTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_idTagActionPerformed

    private void jButton_updateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_updateCategoryActionPerformed

    private void jButton_deleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_deleteCategoryActionPerformed

    private void jtext_idCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_idCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_idCategoriaActionPerformed

    private void jButton_insertCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_insertCategoryActionPerformed

    private void jtext_valor_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_valor_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_valor_categoryActionPerformed

    //Para el filtro de los datos
    private void jText_filterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_filterKeyReleased
        String search=jText_filter.getText();
        TableRowSorter tr=new TableRowSorter(defaultTableModel);
        jTable.setRowSorter(tr);   
        tr.setRowFilter(RowFilter.regexFilter(search));// ,0 column 0
    }//GEN-LAST:event_jText_filterKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJFrame_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJFrame_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_deleteCategory;
    private javax.swing.JButton jButton_deleteComment;
    private javax.swing.JButton jButton_deleteEstafador;
    private javax.swing.JButton jButton_deleteTag;
    private javax.swing.JButton jButton_delete_usuario;
    public javax.swing.JButton jButton_enviarTags;
    public javax.swing.JButton jButton_insertCategory;
    private javax.swing.JButton jButton_menu_categoria;
    private javax.swing.JButton jButton_menu_comment;
    private javax.swing.JButton jButton_menu_estafadores;
    private javax.swing.JButton jButton_menu_tags;
    private javax.swing.JButton jButton_menu_usuarios;
    private javax.swing.JButton jButton_updateCategory;
    private javax.swing.JButton jButton_updateComment;
    private javax.swing.JButton jButton_updateEstafador;
    private javax.swing.JButton jButton_updateTag;
    private javax.swing.JButton jButton_update_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_home;
    private javax.swing.JLabel jLabel_home1;
    private javax.swing.JPanel jPanel_categoria;
    private javax.swing.JPanel jPanel_comentario;
    private javax.swing.JPanel jPanel_contenidoMenu;
    private javax.swing.JPanel jPanel_estafador;
    private javax.swing.JPanel jPanel_filter;
    private javax.swing.JPanel jPanel_menu_lateral;
    private javax.swing.JPanel jPanel_superiorMenu;
    private javax.swing.JPanel jPanel_tabla;
    private javax.swing.JPanel jPanel_tag;
    private javax.swing.JPanel jPanel_usuario;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField_saludo;
    private javax.swing.JTextField jText_filter;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.TextField jtext_comment;
    private java.awt.TextField jtext_comment_comment;
    private java.awt.TextField jtext_datos_1estafador;
    private java.awt.TextField jtext_datos_2estafador;
    private java.awt.TextField jtext_datos_3estafador;
    private java.awt.TextField jtext_email;
    private java.awt.TextField jtext_id;
    private java.awt.TextField jtext_idCategoria;
    private java.awt.TextField jtext_idComment;
    private java.awt.TextField jtext_idEstafador;
    private java.awt.TextField jtext_idTag;
    private java.awt.TextField jtext_name;
    private java.awt.TextField jtext_nick;
    private java.awt.TextField jtext_nick_comment;
    public javax.swing.JTextField jtext_valor_category;
    public javax.swing.JTextField jtext_valor_tag;
    private java.awt.Label label_comment;
    private java.awt.Label label_comment_comment;
    private java.awt.Label label_dato1;
    private java.awt.Label label_dato2;
    private java.awt.Label label_dato3;
    private java.awt.Label label_id;
    private java.awt.Label label_id_Categoria;
    private java.awt.Label label_id_comentario;
    private java.awt.Label label_id_email;
    private java.awt.Label label_id_estafador;
    private java.awt.Label label_id_nick;
    private java.awt.Label label_id_nombre;
    private java.awt.Label label_id_tag;
    private java.awt.Label label_nickPublicado;
    private java.awt.Label label_nombreCategory;
    private java.awt.Label label_nombreTag;
    // End of variables declaration//GEN-END:variables

   
    @Override
    public void mostrarRespuesta(String mensaje) { 
        
        while (defaultTableModel.getRowCount()>0) {
           defaultTableModel.removeRow(0); 
        }
       
        defaultTableModel.setRowCount(0);
        String nombreUsuario;
        String [] str=mensaje.split(SEPARADOR);
        String strProtocolo=str[0];
        
        jPanel_usuario.setVisible(false);
        jPanel_estafador.setVisible(false);
        jPanel_comentario.setVisible(false);
        jPanel_tag.setVisible(false);
        jPanel_categoria.setVisible(false);
        
        jPanel_filter.setVisible(true);
        jPanel_tabla.setVisible(true);
        
        System.out.println("VM mostrarRespuesta server "+mensaje);
        switch (strProtocolo) {
            case LOGIN_OK:
                jPanel_tabla.setVisible(false);
                nombreUsuario=str[1];
                jTextField_saludo.setText("Bienvenido "+nombreUsuario);// o tengo e poner el nick??
                break;
            case CHECKBOX_REGISTRO_TRUE:
                jPanel_tabla.setVisible(false);
                nombreUsuario=str[1];
                jTextField_saludo.setText("Bienvenido "+nombreUsuario);
                break;
            case MENU_USUARIO:   //usuarios    
                usuarioDao.resetUsuario(jtext_id, jtext_name,jtext_nick,jtext_email  );
                jPanel_usuario.setVisible(true);
                jTable.setName(TABLA_USUARIO);
                this.list_usuarios=new ArrayList<>();
                cabecera=new String[]{"ID","NICK", "NOMBRE" , "EMAIL"};
               
                setModeloTabla(this.defaultTableModel, this.jTable,cabecera );
                this.list_usuarios = (ArrayList<Usuario>) usuarioDao.rellenarUsarios(mensaje);
                usuarioDao.setDatosUsuarios(this.defaultTableModel, this.jTable, this.list_usuarios);    
                break; 
            case INSERT_USUARIO: // add alguna tag
                JOptionPane.showMessageDialog(null, MENSAJE_INFORMACION,
                mensaje.substring(7), JOptionPane.INFORMATION_MESSAGE);
                break;    
            case DELETE_USUARIO:  // 
                JOptionPane.showMessageDialog(null, str[2]);
                break;               
            case UPDATE_USUARIO: // add alguna tag
                 JOptionPane.showMessageDialog(null, str[2]);
                break;
             
                //MENU ESTAFADOR CASES
            case MENU_ESTAFADOR:  //estafadores 
                 mostrartable(true);
                 estafadorMenu.resetEstafador( jtext_idEstafador, jtext_datos_1estafador, jtext_datos_2estafador, jtext_datos_3estafador);
                 jTable.setName(TABLA_ESTAFADOR);
                 jPanel_estafador.setVisible(true);
                 
                 this.list_estafadores=new ArrayList<>();
                 cabecera=new String[]{"ID", "Datos del estafador"};
                 setModeloTabla(this.defaultTableModel, this.jTable,cabecera );
                 this.list_estafadores=(ArrayList<Estafador>) estafadorMenu.rellenarTabla(mensaje); 
                 estafadorMenu.modeloTabla(this.defaultTableModel, this.jTable, this.list_estafadores);
                break; 
            case MENU_COMENTARIO: 
                mostrartable(true);  
                comentarioMenu.resetComentario(jtext_idComment, jtext_nick_comment, 
                        jtext_comment_comment, jtext_comment);
                jTable.setName(TABLA_COMENTARIOS);
                jPanel_comentario.setVisible(true);
                
                this.list_comments=new ArrayList<>();
                cabecera=new String[]{ "ID",  "NICK-COMMENT","CONTENIDO"};
                setModeloTabla(this.defaultTableModel, this.jTable, cabecera);
                this.list_comments=(ArrayList<Comentario>) comentarioMenu.rellenarComments(mensaje);
                comentarioMenu.setComments(this.defaultTableModel, this.jTable, this.list_comments);
                break;
              case DELETE_COMMENT:  // DELETE_TAG:OK/NOTOK:respuesta_server
                JOptionPane.showMessageDialog(null, str[2]);
                break;     
            case UPDATE_COMMENT: //UPDATE_TAG:OK/NOTOK:respuesta_server
                 JOptionPane.showMessageDialog(null, str[2]); 
                 break;
                
                
                
             
                //MENU TAG cases
            case MENU_TAG:  // add alguna tag
               // resetLogin(); // cambiar nombre
                tagMenu.resetTag(jtext_idTag,jtext_valor_tag);
                jPanel_tag.setVisible(true);
                cabecera=new String[]{"ID","VALOR"};
                mostrartable(true);
                jTable.setName(TABLA_TAGS);
                setModeloTabla(this.defaultTableModel, this.jTable, cabecera);
                this.list_tags=(ArrayList<Tag>) tagMenu.rellenarTabla(mensaje);
                tagMenu.modeloTabla(this.defaultTableModel, this.jTable, this.list_tags);
                break;
            case INSERT_TAG: // (INSERT_TAG:OK/NOT_OK:Tag insertada
                JOptionPane.showMessageDialog(null, str[2]);
                tagMenu.resetTag(jtext_idTag,jtext_valor_tag);
                //volver rellenar la tabla
                jPanel_tag.setVisible(true);
                cabecera=new String[]{"ID","VALOR"};
                mostrartable(true);
                setModeloTabla(this.defaultTableModel, this.jTable, cabecera);
                tagMenu.modeloTabla(this.defaultTableModel, this.jTable, this.list_tags);
                break;    
             case DELETE_TAG:  // DELETE_TAG:OK/NOTOK:respuesta_server
                JOptionPane.showMessageDialog(null, str[2]);
                break;     
            case UPDATE_TAG: //UPDATE_TAG:OK/NOTOK:respuesta_server
                 JOptionPane.showMessageDialog(null, str[2]);
                break;
                
                
            case MENU_CATEGORIA:
                categoriaMenu.resetCategoria(jtext_idCategoria,jtext_valor_category);
                jPanel_categoria.setVisible(true);
                cabecera=new String[]{"ID","VALOR"};
                mostrartable(true);
                this.jTable.setName(TABLA_CATEGORIA);
                setModeloTabla(this.defaultTableModel, this.jTable, cabecera);
                this.list_category= (ArrayList<Categoria>) categoriaMenu.rellenarTabla(mensaje);
                categoriaMenu.modeloTabla(this.defaultTableModel, this.jTable, this.list_category);
                System.out.println("....."+MENU_CATEGORIA);
                break;
             case INSERT_CATEGORIA: // (INSERT_CATEGORIA:OK/NOT_OK:Tag insertada
                JOptionPane.showMessageDialog(null, str[2]);
                categoriaMenu.resetCategoria(jtext_idCategoria,jtext_valor_category);
                //volver rellenar la tabla
                jPanel_categoria.setVisible(true);
                cabecera=new String[]{"ID","VALOR"};
                mostrartable(true);
                setModeloTabla(this.defaultTableModel, this.jTable, cabecera);
                categoriaMenu.modeloTabla(this.defaultTableModel, this.jTable, this.list_category);
                break;     
            case DELETE_CATEGORIA:  // DELETE_CATEGORIA:OK/NOTOK:respuesta_server
                JOptionPane.showMessageDialog(null, str[2]);
                break;
                
            case UPDATE_CATEGORIA: //UPDATE_CATEGORIA:OK/NOTOK:respuesta_server
                 JOptionPane.showMessageDialog(null, str[2]);
                break;
                
           
            default:
                System.err.println("ERROR vista Menu->default: " );
        }     
    }
  
    public void mostrartable(boolean visble){
         jTable.setVisible(visble);
         jTable.getTableHeader().setVisible(visble); 
  
    }
    public void setModeloTabla(DefaultTableModel defaultTableModel, JTable jTable, String[] cabecera) {
        JTableHeader th;
        th = this.jTable.getTableHeader();
        th.setReorderingAllowed(false);// probando
     
         
        Font fuente = new Font("Verdana", Font.BOLD, 12);
        th.setFont(fuente);
        th.setBackground(Color.blue);
        th.setSize(100, 40);
        this.jTable.getTableHeader().setForeground(Color.white);
        this.defaultTableModel.setColumnIdentifiers(cabecera);        
        this.jTable.setModel(defaultTableModel);
        
        
//     solo imprime
//this.jTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//    @Override
//    public void valueChanged(ListSelectionEvent e) {
//        String nombre = jTable.getValueAt(jTable.getSelectedRow(), 0).toString();
//        String semestre = jTable.getValueAt(jTable.getSelectedRow(), 1).toString();
//        String especialidad = "water";//jTable.getValueAt(jTable.getSelectedRow(), 2).toString();
//        System.out.println("Nombre: " + nombre + " | Semestre: " + semestre + " | Especialidad: " + especialidad);
//    }
//});
   }

   
    @Override
    public void resetLogin() {

    }

    @Override
    public void setControlador(ControladorCliente controlador) {
        this.controlador = controlador;
    }

    @Override
    public void hacerVisible() {
        setVisible(true);  
    }
    
    @Override
    public void inicializar(){
        jButton_menu_usuarios.addActionListener(controlador);
        jButton_menu_estafadores.addActionListener(controlador);
        jButton_menu_comment.addActionListener(controlador);
        jButton_menu_tags.addActionListener(controlador);
        jButton_menu_categoria.addActionListener(controlador);
        
        jButton5.addActionListener(controlador);
        jButton_delete_usuario.addActionListener(controlador);
        jButton_update_usuario.addActionListener(controlador);
        
        jButton_updateComment.addActionListener(controlador);
        jButton_deleteComment.addActionListener(controlador);
        
        jButton_enviarTags.addActionListener(controlador); 
        jButton_updateTag.addActionListener(controlador);
        jButton_deleteTag.addActionListener(controlador);
        
        jButton_insertCategory.addActionListener(controlador); 
        jButton_updateCategory.addActionListener(controlador);
        jButton_deleteCategory.addActionListener(controlador); 
     
    }

    public String getMensaje() {
       return mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

   
    @Override
    public String getMensajeAEnviar() {
    this.mensaje="";
        switch(jTable.getName()){
            case TABLA_USUARIO:
                String id=jtext_id.getText().toString();
                String name=jtext_name.getText().toString();
                String nick=jtext_nick.getText().toString();
                String email=jtext_email.getText().toString();
                this.mensaje=id+SEPARADOR+name+SEPARADOR+nick+SEPARADOR+email; 
                break;
             case TABLA_ESTAFADOR:
//                 String id=jtext_id.getText().toString();
//                 String name=jtext_name.getText().toString();
//                 String nick=jtext_nick.getText().toString();
//                 String email=jtext_email.getText().toString();
//            this.mensaje=id+SEPARADOR+name+SEPARADOR+nick+SEPARADOR+email; 
                break; 
             case TABLA_TAGS:
                 String idTag=jtext_idTag.getText().toString();
                 String tagName=jtext_valor_tag.getText().toString();
                 if(!idTag.isEmpty())// si id !isEmpty-> update
                     this.mensaje=idTag+SEPARADOR+tagName;
                 else{//= un insert
                      this.mensaje=tagName+SEPARADOR;
                 }
                 break;
             case TABLA_CATEGORIA:
                  String idCategory=jtext_idCategoria.getText().toString();
                  String categoryName=jtext_valor_category.getText().toString();
                  if(!idCategory.isEmpty())
                     this.mensaje=idCategory+SEPARADOR+categoryName;
                  else{
                      this.mensaje=categoryName+SEPARADOR;
                 }
                 break;
            case TABLA_COMENTARIOS :
                  String idComment=jtext_idComment.getText().toString();
                  String nickc=jtext_nick_comment.getText().toString();
                  String contenido=jtext_comment_comment.getText().toString();
                  if(!idComment.isEmpty())
                     this.mensaje=idComment+SEPARADOR+contenido;//+nickc+SEPARADOR
                  else{
                      this.mensaje=idComment+SEPARADOR;
                 }
                 break;
            
        }      
        return  this.mensaje;
    }

    @Override
    public void cerrar() {
         this.dispose();
    }

    @Override
    public void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
    
    public void ocultarCamposestafador(boolean estado){
         jtext_datos_2estafador.setVisible(estado);
         jtext_datos_3estafador.setVisible(estado);
         label_dato2.setVisible(estado);
         label_dato3.setVisible(estado);
    }

    
    private   String[] cabecera; 
    private DefaultTableModel defaultTableModel=new DefaultTableModel();
    private ArrayList<Usuario> list_usuarios;
    private ArrayList<Estafador> list_estafadores;
    private ArrayList<Comentario> list_comments=new ArrayList<>();
    private ArrayList<Tag> list_tags;
     private ArrayList<Categoria> list_category;
    private String mensaje;

    private UsuarioTabla usuarioDao=new UsuarioTabla();
    private EstafadorTabla estafadorMenu=new EstafadorTabla();
    private ComentarioTabla comentarioMenu=new ComentarioTabla();
    private TagTabla tagMenu=new TagTabla();
    private CategoriaTabla categoriaMenu=new CategoriaTabla();

    
    //poner en login
    @Override
    public void itemStateChanged(ItemEvent e) {

    }

}
